### ISSUE TITLE
CherryPy Autoloader dies with bcrypt

### ISSUE THREAD

**Issue by crocodilered** [pyca/bcrypt#134]
I have project on CherryPy and want AuthTool to use bcrypt module for password processing. But when I put "import bcrypt" line into AuthTool.py the CherryPy tells me:

```
[17/Nov/2017:18:07:42] ENGINE Error in background task thread function <bound method Autoreloader.run of <cherrypy.process.plugins.Autoreloader object at 0x00000245AF676390>>.
AttributeError: cffi library '_bcrypt' has no function, constant or global variable named '__loader__'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Serge\AppData\Local\Programs\Python\Python36\lib\site-packages\cherrypy\process\plugins.py", line 522, in run
    self.function(*self.args, **self.kwargs)
  File "C:\Users\Serge\AppData\Local\Programs\Python\Python36\lib\site-packages\cherrypy\process\plugins.py", line 654, in run
    for filename in self.sysfiles() | self.files:
  File "C:\Users\Serge\AppData\Local\Programs\Python\Python36\lib\site-packages\cherrypy\process\plugins.py", line 638, in sysfiles
    hasattr(m, '__loader__') and
SystemError: <built-in function hasattr> returned a result with an error set

Exception in thread Autoreloader:
AttributeError: cffi library '_bcrypt' has no function, constant or global variable named '__loader__'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Serge\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\Serge\AppData\Local\Programs\Python\Python36\lib\site-packages\cherrypy\process\plugins.py", line 522, in run
    self.function(*self.args, **self.kwargs)
  File "C:\Users\Serge\AppData\Local\Programs\Python\Python36\lib\site-packages\cherrypy\process\plugins.py", line 654, in run
    for filename in self.sysfiles() | self.files:
  File "C:\Users\Serge\AppData\Local\Programs\Python\Python36\lib\site-packages\cherrypy\process\plugins.py", line 638, in sysfiles
    hasattr(m, '__loader__') and
SystemError: <built-in function hasattr> returned a result with an error set
```

I have 
3.6 python.
bcrypt (3.1.4)
CherryPy (11.1.0)
cffi (1.11.2)

Is there something to do with this?

**Comment by webknjaz** [comment]
@crocodilered I'm pretty sure that it's fixed in the modern versions CherryPy.

**Comment by alex** [comment]
Sorry we neglected this bug for 1.5 years. I'm glad to hear it's fixed.
