### ISSUE TITLE
Missing header

### ISSUE THREAD

**Issue by ecowan** [pyca/bcrypt#168]
Bcrypt is failing within a Django 2.0.8 project with the following:

`from venv/lib/python3.7/site-packages/bcrypt/__pycache__/_cffi_677459_d17cc0.c:2:
venv/lib/python3.7/site-packages/bcrypt/crypt_blowfish-1.2/crypt.h:17:10: fatal error: gnu-crypt.h: 
No such file or directory
 #include <gnu-crypt.h>
          ^~~~~~~~~~~~~
compilation terminated.
Internal Server Error: /users/register/
Traceback (most recent call last):
  File "/usr/lib/python3.7/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/usr/lib/python3.7/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib/python3.7/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 1`

this has also been reported in another repo: https://github.com/docker-library/python/issues/287

**Comment by reaperhulk** [comment]
Try installing the latest version, the version you're trying to install is almost 6 years old I believe?
