### ISSUE TITLE
M1 Silicon | Python 3.9.x Support

### ISSUE THREAD

**Issue by selected-pixel-jameson** [pyca/bcrypt#251]
Is there a roadmap for updating this library to support Python 3.9.x so that we can build projects using the new M1 processors?

**Comment by reaperhulk** [comment]
This project supports 3.9 without any issues in the released version. We don't distribute wheels at this time, but it compiles without issue on my M1 mini. The problems I've seen people have with compilation are usually due to `cffi` pathing issues. What error are you seeing?

**Comment by selected-pixel-jameson** [comment]
I'm using pyenv to manage the python environment version. I currently have the python environment set to 3.9.4

When I run `pip install -r requirements.txt` I get the following error.

```
Collecting bcrypt==3.2.0
  Using cached bcrypt-3.2.0.tar.gz (42 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/buildagent/.pyenv/versions/3.9.4/bin/python /Users/buildagent/.pyenv/versions/3.9.4/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/lj/9yvv5_653rq99n55nk42lnpr0000gn/T/tmpclsz26cr
         cwd: /private/var/folders/lj/9yvv5_653rq99n55nk42lnpr0000gn/T/pip-install-cnh10b9a/bcrypt_9f139a33b16044c8bb45cbd8e6f5e0eb
    Complete output (38 lines):
    Traceback (most recent call last):
      File "/Users/buildagent/.pyenv/versions/3.9.4/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/Users/buildagent/.pyenv/versions/3.9.4/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/Users/buildagent/.pyenv/versions/3.9.4/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/private/var/folders/lj/9yvv5_653rq99n55nk42lnpr0000gn/T/pip-build-env-d1ju46fq/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 166, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/private/var/folders/lj/9yvv5_653rq99n55nk42lnpr0000gn/T/pip-build-env-d1ju46fq/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 150, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 46, in <module>
        setup(
      File "/private/var/folders/lj/9yvv5_653rq99n55nk42lnpr0000gn/T/pip-build-env-d1ju46fq/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/Users/buildagent/.pyenv/versions/3.9.4/lib/python3.9/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/private/var/folders/lj/9yvv5_653rq99n55nk42lnpr0000gn/T/pip-build-env-d1ju46fq/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 434, in __init__
        _Distribution.__init__(self, {
      File "/Users/buildagent/.pyenv/versions/3.9.4/lib/python3.9/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/private/var/folders/lj/9yvv5_653rq99n55nk42lnpr0000gn/T/pip-build-env-d1ju46fq/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 743, in finalize_options
        ep(self)
      File "/private/var/folders/lj/9yvv5_653rq99n55nk42lnpr0000gn/T/pip-build-env-d1ju46fq/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 750, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/private/var/folders/lj/9yvv5_653rq99n55nk42lnpr0000gn/T/pip-build-env-d1ju46fq/overlay/lib/python3.9/site-packages/cffi/setuptools_ext.py", line 219, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/private/var/folders/lj/9yvv5_653rq99n55nk42lnpr0000gn/T/pip-build-env-d1ju46fq/overlay/lib/python3.9/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/private/var/folders/lj/9yvv5_653rq99n55nk42lnpr0000gn/T/pip-build-env-d1ju46fq/overlay/lib/python3.9/site-packages/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "src/build_bcrypt.py", line 21, in <module>
        ffi = FFI()
      File "/private/var/folders/lj/9yvv5_653rq99n55nk42lnpr0000gn/T/pip-build-env-d1ju46fq/overlay/lib/python3.9/site-packages/cffi/api.py", line 48, in __init__
        import _cffi_backend as backend
    ImportError: dlopen(/private/var/folders/lj/9yvv5_653rq99n55nk42lnpr0000gn/T/pip-build-env-d1ju46fq/overlay/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so, 2): no suitable image found.  Did find:
    	/private/var/folders/lj/9yvv5_653rq99n55nk42lnpr0000gn/T/pip-build-env-d1ju46fq/overlay/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so: mach-o, but wrong architecture
    	/private/var/folders/lj/9yvv5_653rq99n55nk42lnpr0000gn/T/pip-build-env-d1ju46fq/overlay/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so: mach-o, but wrong architecture
    ----------------------------------------

```
```
WARNING: Discarding https://files.pythonhosted.org/packages/d8/ba/21c475ead997ee21502d30f76fd93ad8d5858d19a3fad7cd153de698c4dd/bcrypt-3.2.0.tar.gz#sha256=5b93c1726e50a93a033c36e5ca7fdcd29a5c7395af50a6892f5d9e7c6cfbfb29 (from https://pypi.org/simple/bcrypt/) (requires-python:>=3.6). Command errored out with exit status 1: /Users/buildagent/.pyenv/versions/3.9.4/bin/python /Users/buildagent/.pyenv/versions/3.9.4/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/lj/9yvv5_653rq99n55nk42lnpr0000gn/T/tmpclsz26cr Check the logs for full command output.
```
```
ERROR: Could not find a version that satisfies the requirement bcrypt==3.2.0
ERROR: No matching distribution found for bcrypt==3.2.0
```

**Comment by reaperhulk** [comment]
```
    ImportError: dlopen(/private/var/folders/lj/9yvv5_653rq99n55nk42lnpr0000gn/T/pip-build-env-d1ju46fq/overlay/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so, 2): no suitable image found.  Did find:
```

This is unrelated to bcrypt and is a problem with installing cffi (where it builds but then fails on import). Try following the instructions I wrote up here: https://stackoverflow.com/a/66055389/369874

**Comment by selected-pixel-jameson** [comment]
Great! Thank you!

Jameson W Parker

**Comment by iam-py-test** [comment]
> 
> Great! Thank you! Jameson W Parker
> […](#)
> On Apr 16, 2021, at 3:33 PM, Paul Kehrer ***@***.***> wrote: ﻿ ImportError: dlopen(/private/var/folders/lj/9yvv5_653rq99n55nk42lnpr0000gn/T/pip-build-env-d1ju46fq/overlay/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so, 2): no suitable image found. Did find: This is unrelated to bcrypt and is a problem with installing cffi (where it builds but then fails on import). Try following the instructions I wrote up here: https://stackoverflow.com/a/66055389/369874 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

@selected-pixel-jameson you might want to edit your comment because it includes your name, and (based on the fact that you have not set the name on your profile) you might want to delete that.

**Comment by selected-pixel-jameson** [comment]
@iam-py-test Thank you. Can you please delete your comment?

**Comment by levrik** [comment]
@reaperhulk Sadly updating to last version of `cffi` doesn't work. It includes wheels for M1 but it doesn't seem to fix the issues here.
