### ISSUE TITLE
Error installing bcrypt on PyPy

### ISSUE THREAD

**Issue by yogevyuval** [pyca/bcrypt#289]
Trying to install latest bcrypt on pypy results with the following error:
```
  Traceback (most recent call last):
    File "/opt/pypy/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/opt/pypy/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/opt/pypy/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
      return hook(metadata_directory, config_settings)
    File "/tmp/pip-build-env-agt_0oqx/overlay/site-packages/setuptools/build_meta.py", line 188, in prepare_metadata_for_build_wheel
      self.run_setup()
    File "/tmp/pip-build-env-agt_0oqx/overlay/site-packages/setuptools/build_meta.py", line 174, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 76, in <module>
      cmdclass={"test": PyTest},
    File "/tmp/pip-build-env-agt_0oqx/overlay/site-packages/setuptools/__init__.py", line 155, in setup
      return distutils.core.setup(**attrs)
    File "/tmp/pip-build-env-agt_0oqx/overlay/site-packages/setuptools/_distutils/core.py", line 109, in setup
      _setup_distribution = dist = klass(attrs)
    File "/tmp/pip-build-env-agt_0oqx/overlay/site-packages/setuptools/dist.py", line 462, in __init__
      for k, v in attrs.items()
    File "/tmp/pip-build-env-agt_0oqx/overlay/site-packages/setuptools/_distutils/dist.py", line 293, in __init__
      self.finalize_options()
    File "/tmp/pip-build-env-agt_0oqx/overlay/site-packages/setuptools/dist.py", line 851, in finalize_options
      ep(self)
    File "/tmp/pip-build-env-agt_0oqx/overlay/site-packages/setuptools/dist.py", line 871, in _finalize_setup_keywords
      self._install_dependencies(ep)
    File "/tmp/pip-build-env-agt_0oqx/overlay/site-packages/setuptools/dist.py", line 881, in _install_dependencies
      for req in map(requirements.Requirement, always_iterable(ep.dist.requires))
    File "/tmp/pip-build-env-agt_0oqx/overlay/site-packages/setuptools/dist.py", line 879, in <setcomp>
      reqs = {
    File "/tmp/pip-build-env-agt_0oqx/overlay/site-packages/setuptools/_vendor/packaging/requirements.py", line 105, in __init__
      f'Parse error at "{ requirement_string[e.loc : e.loc + 8]!r}": {e.msg}'
  setuptools._vendor.packaging.requirements.InvalidRequirement: Parse error at "''": Expected W:(abcd...)
```

bcrypt 3.1.14 works

Any idea what's going on here?

**Comment by alex** [comment]
https://github.com/pypa/setuptools/issues/3107

Looks like there's a new version of setuptools that should fix it.
