### ISSUE TITLE
Error when using bcrypt to salt and hash password

### ISSUE THREAD

**Issue by londarks** [pyca/bcrypt#625]
i am having problem to use bcrypt in a simple example

```python
import bcrypt
password = b"super secret password"
# Hash a password for the first time, with a randomly-generated salt
hashed = bcrypt.hashpw(password, bcrypt.gensalt())
# Check that an unhashed password matches one that has previously been
# hashed
if bcrypt.checkpw(password, hashed):
    print("It Matches!")
else:
    print("It Does not Match :(")
```

```bash
Traceback (most recent call last):
  File "/home/londarks/teste.py", line 4, in <module>
    hashed = bcrypt.hashpw(password, bcrypt.gensalt())
  File "/home/londarks/env/lib/python3.10/site-packages/bcrypt/__init__.py", line 60, in gensalt
    output = _bcrypt.encode_base64(salt)
AttributeError: module 'bcrypt._bcrypt' has no attribute 'encode_base64'
```

my python is 3.10 and  bcrypt-4.0.1

**Comment by alex** [comment]
This indicates that somehow your installation was corrupted. Can you provide instructinos for us to reproduce this, starting with a new virtualenv?
